name: Daily Stocking Data Update

on:
  schedule:
    # Run every day at 6:30 PM Mountain Time (1:30 AM UTC next day)
    - cron: '30 1 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pdfplumber

      - name: Run daily update
        run: |
          python weekly_update.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add stocking_data_clean.json stocking_data.json public/
          git diff --staged --quiet || git commit -m "Daily stocking data update - $(date +'%Y-%m-%d')"
          git push
